# Generated by Django 5.1.2 on 2024-11-19 21:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('idade', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(18)])),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', models.CharField(max_length=12)),
                ('setor', models.CharField(choices=[('ADM', 'ADMINISTRAÇÃO'), ('COM', 'COMERCIAL'), ('PRD', 'PRODUÇÃO'), ('RH', 'RECURSOS HUMANOS'), ('FIN', 'FINANCEIRO')], default=None, max_length=5)),
                ('cargo', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos_rh/funcionario/nome')),
                ('usuario', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
