# Generated by Django 5.1.2 on 2024-11-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Recursos Humanos'},
        ),
    ]
