# Generated by Django 5.1.2 on 2024-11-20 20:34

import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfilusuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_documento',
            field=models.CharField(choices=[('RELATORIOS', 'RELATORIOS'), ('PEDIDO', 'PEDIDO'), ('NOTAS REEMBOLSO', 'NOTAS DE REEMBOLSO'), ('NF PARA FATURA', 'NOTAS DE FATURAMENTO'), ('ACEITE', 'ACEITES'), ('DIVERSOS', 'ACEITES')], default='diversos', max_length=25),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='documentos',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=utils.tools_utils.docs_rh_load_path, verbose_name='Documentos '),
        ),
    ]
