# Generated by Django 5.1.2 on 2024-11-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfilusuario_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='objeto',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_documento',
            field=models.CharField(choices=[('REGISTRO', 'Docs admissão'), ('COMPROVANTES', 'COMPROVANTES'), ('REEMBOLSO', 'NOTAS DE REEMBOLSO'), (' SAUDE', 'DOCS MEDICOS'), ('ADVERTENCIAS', 'ADVS E MULTAS'), ('JUDICIAIS', 'DOCS JUDICIAIS')], default='diversos', max_length=25),
        ),
    ]
