# Generated by Django 5.1.2 on 2024-11-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_perfilusuario_objeto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='objeto',
            new_name='ocorrencias',
        ),
    ]
