# Generated by Django 5.1.2 on 2024-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_rename_objeto_perfilusuario_ocorrencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_documento',
            field=models.CharField(choices=[('REGISTRO', 'DOCS ADMISSAO'), ('COMPROVANTES', 'COMPROVANTES'), ('REEMBOLSO', 'NOTAS DE REEMBOLSO'), (' SAUDE', 'DOCS MEDICOS'), ('ADVERTENCIAS', 'ADVS E MULTAS'), ('JUDICIAIS', 'DOCS JUDICIAIS')], default='diversos', max_length=25),
        ),
    ]
