# Generated by Django 5.1.2 on 2024-12-10 19:38

import django.db.models.deletion
import utils.tools_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_perfilusuario_tipo_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastrofuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('n_residencial', models.CharField(blank=True, max_length=250, null=True)),
                ('bairro', models.CharField(blank=True, max_length=250, null=True)),
                ('cidade', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=None, max_length=2)),
                ('complemento', models.CharField(blank=True, max_length=250, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=12)),
                ('rg', models.CharField(max_length=12)),
                ('setor', models.CharField(choices=[('ADM', 'ADMINISTRAÇÃO'), ('COM', 'COMERCIAL'), ('OPR', 'OPERACIONAL'), ('RH', 'RECURSOS HUMANOS'), ('FIN', 'FINANCEIRO')], default=None, max_length=5)),
                ('nacional', models.CharField(choices=[('Nacional', 'Brasileiro'), ('Estrangeiro', 'Estrangeiro')], default=None, max_length=25)),
                ('cargo', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(blank=True, choices=[('', ''), ('REGISTRO', 'DOCS ADMISSAO'), ('COMPROVANTES', 'COMPROVANTES'), ('REEMBOLSO', 'NOTAS DE REEMBOLSO'), (' SAUDE', 'DOCS MEDICOS'), ('ADVERTENCIAS', 'ADVS E MULTAS'), ('JUDICIAIS', 'DOCS JUDICIAIS')], default='diversos', max_length=25)),
                ('documentos', models.FileField(blank=True, max_length=255, null=True, upload_to=utils.tools_utils.docs_rh_load_path, verbose_name='Documentos ')),
                ('ocorrencias', models.TextField(blank=True, default='', max_length=5000)),
                ('nome_mae', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nome_pais', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('celular', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=250, null=True)),
                ('estado_civil', models.CharField(choices=[('solteiro(a)', 'solteiro(a)'), ('casado(a)', 'casado(a)'), ('divorciado(a)', 'divorciado(a)'), ('viuvo(a)', 'viuvo(a)'), ('nao informado', 'nao informado')], default=None, max_length=250, null=True)),
                ('formacao_academica', models.CharField(choices=[('fundamental incompleto', 'fundamental inccompleto'), ('fundamental completo', 'fundamental completo'), ('Ensino Medio incompleto', 'Ensino Medio inccompleto'), ('Ensino medio Completo', 'Ensino medio Completo'), ('Gradução superior incompleta', 'Graduação superior inccompleto'), ('Bacharelado', 'Bacharelado'), ('Pos/especialização', 'pos/especialização')], default=None, max_length=250, null=True)),
                ('curso_superior', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('pos_especializacao', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('ctps', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('banco', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('agencia', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('n_conta_banco', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('nomecompleto', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Recursos Humanos',
            },
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
