# Generated by Django 5.1.2 on 2024-12-12 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_cadastrofuncionario_delete_perfilusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrofuncionario',
            old_name='estado',
            new_name='UF',
        ),
        migrations.RenameField(
            model_name='cadastrofuncionario',
            old_name='documentos',
            new_name='arquivos',
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='categoria_cnh',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='cpf_conjuge',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='data_emissao_rg',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='data_nascimento_conjuge',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='documento',
            field=models.CharField(blank=True, choices=[('', ''), ('CTPS', 'CARTEIRA DE TRABALHO'), ('RG', 'RG'), ('CPF', 'CPF'), (' TITULO-ELEITOR', 'TITULO ELEITOR'), ('CERTIFICADO RESERVISTA', 'CAM'), ('CERTIFICADOS', 'CERTIFICADOS')], default='diversos', max_length=100),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='n_cam',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='n_cnh',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='n_titulo_eleitor',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='nome_conjuge',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='orgao_expedidor_rg',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='pis',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='reservista',
            field=models.BooleanField(default=False, verbose_name='Reservista'),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='rg_conjuge',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='secao',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='serie',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='uf_emissao_ctps',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='uf_rg',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='vale_alimentacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='vale_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='vencimento_cnh',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='zona_eleitor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='n_conta_banco',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Numero da conta'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='nomecompleto',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='depenente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_depenente', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Nome')),
                ('cpf_dependente', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='CPF')),
                ('grau_relacional', models.CharField(blank=True, choices=[('filho', 'filho'), ('genitor', 'genitor'), ('conjuge', 'conjuge'), ('avos', 'avos'), ('bisavos', 'bisavos')], default=None, max_length=250, null=True, verbose_name='Grau relacional')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.cadastrofuncionario')),
            ],
        ),
        migrations.CreateModel(
            name='uniformes_EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('uniforme', 'uniforme'), ('EPI', 'EPI')], default=None, max_length=250, null=True)),
                ('acessorios', models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='Acessorios')),
                ('peca_superior', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Peca superior')),
                ('tamanho_pecasuperior', models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXG', 'EXG')], default=None, max_length=250, null=True, verbose_name='Tamanho peça superior')),
                ('peca_inferior', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Peca inferior')),
                ('tamanho_pecasupinferior', models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXG', 'EXG')], default=None, max_length=250, null=True, verbose_name='Tamanho peça inferior')),
                ('sapatos', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Sapatos')),
                ('tamanho_sapatos', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Tamanho')),
                ('data_entrega', models.DateField()),
                ('data_troca', models.DateField()),
                ('motivo_troca', models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='Motivo troca')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.cadastrofuncionario')),
            ],
        ),
    ]
