# Generated by Django 5.1.2 on 2024-12-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_rename_estado_cadastrofuncionario_uf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dependente', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Nome dependente')),
                ('cpf_dependente', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='CPF_dependente')),
                ('grau_relacional', models.CharField(blank=True, choices=[('filho', 'filho'), ('genitor', 'genitor'), ('conjuge', 'conjuge'), ('avos', 'avos'), ('bisavos', 'bisavos')], default=None, max_length=250, null=True, verbose_name='Grau relacional')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.cadastrofuncionario')),
            ],
        ),
        migrations.DeleteModel(
            name='depenente',
        ),
    ]
