# Generated by Django 5.1.2 on 2024-12-12 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_dependente_delete_depenente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('', ''), ('REGISTRO', 'REGISTRO'), ('COMPROVANTES', 'COMPROVANTES'), ('REEMBOLSO', 'NOTAS DE REEMBOLSO'), (' SAUDE', 'DOCS MEDICOS'), ('ADVERTENCIAS', 'ADVS E MULTAS'), ('JUDICIAIS', 'DOCS JUDICIAIS')], default='diversos', max_length=125),
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.cadastrofuncionario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
