# Generated by Django 5.1.2 on 2024-12-13 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_alter_cadastrofuncionario_tipo_documento_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniformes_epi',
            options={'verbose_name': 'Uniforme', 'verbose_name_plural': 'Uniformes'},
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='usuario',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
