# Generated by Django 5.1.2 on 2024-12-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_alter_uniformes_epi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='vale_alimentacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='vale_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('senha', models.CharField(max_length=12)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.cadastrofuncionario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
