# Generated by Django 5.1.2 on 2024-12-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_remove_cadastrofuncionario_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuario_sistema',
        ),
    ]
