# Generated by Django 5.1.2 on 2024-12-15 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_rename_usuario_usuario_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='uf_emissao_ctps',
        ),
        migrations.RemoveField(
            model_name='usuario_sistema',
            name='senha',
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='nomecompleto',
            field=models.CharField(max_length=50, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('', ''), ('REGISTRO', 'REGISTRO'), ('COMPROVANTES', 'COMPROVANTES'), ('REEMBOLSO', 'NOTAS DE REEMBOLSO'), (' SAUDE', 'DOCS MEDICOS'), ('ADVERTENCIAS', 'ADVS E MULTAS'), ('JUDICIAIS', 'DOCS JUDICIAIS'), ('CERTIFICADOS', 'CERTIFICADOS')], default='diversos', max_length=125, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dependente', to='perfil.cadastrofuncionario'),
        ),
        migrations.AlterField(
            model_name='uniformes_epi',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uniforme_epi', to='perfil.cadastrofuncionario'),
        ),
        migrations.AlterField(
            model_name='usuario_sistema',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='perfil.cadastrofuncionario'),
        ),
        migrations.AlterField(
            model_name='usuario_sistema',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
