# Generated by Django 5.1.2 on 2024-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_remove_cadastrofuncionario_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='cpf_conjuge',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='data_nascimento_conjuge',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='n_cam',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='nome_conjuge',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='reservista',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='rg_conjuge',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='secao',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='uf_rg',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='zona_eleitor',
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='modal_transporte',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='n_titulo_eleitor',
            field=models.CharField(max_length=12, verbose_name='Titulo de eleitor'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='nome_mae',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='nome_pais',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('', ''), ('REGISTRO', 'REGISTRO'), ('COMPROVANTES', 'COMPROVANTES'), ('REEMBOLSO', 'NOTAS DE REEMBOLSO'), (' SAUDE', 'DOCS MEDICOS'), ('ADVERTENCIAS', 'ADVS E MULTAS'), ('JUDICIAIS', 'DOCS JUDICIAIS'), ('CERTIFICADOS', 'CERTIFICADOS'), ('Documentos dependente', 'Documentos dependente')], default='diversos', max_length=125, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='grau_relacional',
            field=models.CharField(blank=True, choices=[('filho', 'filho'), ('genitor', 'genitor'), ('conjuge', 'conjuge'), ('avos', 'avos'), ('bisavos', 'bisavos')], default=None, max_length=250, null=True, verbose_name='Relação'),
        ),
    ]
