# Generated by Django 5.1.2 on 2024-12-15 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_remove_cadastrofuncionario_cpf_conjuge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='curso_superior',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='nacional',
        ),
        migrations.RemoveField(
            model_name='cadastrofuncionario',
            name='pos_especializacao',
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='curso_formacao',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Formaçao'),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('Brasileiro', 'Brasileiro'), ('Estrangeiro', 'Estrangeiro')], default=None, max_length=250, null=True, verbose_name='nacionalidade'),
        ),
        migrations.AddField(
            model_name='cadastrofuncionario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'masculino'), ('feminino', 'feminino'), ('Nao Binario(a)(e)', 'Nao Binario(a)(e)'), ('Nao identificar', 'Nao Identificar')], default=None, max_length=250, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='UF',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=None, max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='agencia',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='bairro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='banco',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='categoria_cnh',
            field=models.CharField(max_length=50, verbose_name='categoria CNH'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='celular',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='cpf',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='ctps',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='CTPS'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='data_emissao_rg',
            field=models.DateField(verbose_name='data emissao rg'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro(a)', 'solteiro(a)'), ('casado(a)', 'casado(a)'), ('divorciado(a)', 'divorciado(a)'), ('viuvo(a)', 'viuvo(a)'), ('nao informado', 'nao informado')], default=None, max_length=250, null=True, verbose_name='estado civil'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='formacao_academica',
            field=models.CharField(choices=[('fundamental incompleto', 'fundamental inccompleto'), ('fundamental completo', 'fundamental completo'), ('Ensino Medio incompleto', 'Ensino Medio inccompleto'), ('Ensino medio Completo', 'Ensino medio Completo'), ('Gradução superior incompleta', 'Graduação superior inccompleto'), ('Bacharelado', 'Bacharelado'), ('Pos/especialização', 'pos/especialização')], default=None, max_length=250, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='modal_transporte',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='Modalidade de transporte'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='n_cnh',
            field=models.CharField(max_length=50, verbose_name='numero CNH'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='n_residencial',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='numero residencial'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='naturalidade'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='ocorrencias',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='ocorrencias'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='orgao_expedidor_rg',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='orgao expedidor rg'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='pis',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Pis'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='rg',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='rg'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='serie',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='setor',
            field=models.CharField(choices=[('ADM', 'ADMINISTRAÇÃO'), ('COM', 'COMERCIAL'), ('OPR', 'OPERACIONAL'), ('RH', 'RECURSOS HUMANOS'), ('FIN', 'FINANCEIRO')], default=None, max_length=5, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='telefone',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='vale_alimentacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Vale Alimentação'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='vale_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Vale transporte'),
        ),
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='vencimento_cnh',
            field=models.DateField(verbose_name='vencimento CNH'),
        ),
        migrations.AlterField(
            model_name='usuario_sistema',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='perfil.cadastrofuncionario', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='usuario_sistema',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
