# Generated by Django 5.1.2 on 2024-12-26 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0016_remove_cadastrofuncionario_curso_superior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependente', to='perfil.cadastrofuncionario'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='nome_dependente',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Nome dependente'),
        ),
    ]
