# Generated by Django 5.1.2 on 2024-12-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0017_alter_dependente_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformes_epi',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniforme_epi', to='perfil.cadastrofuncionario'),
        ),
    ]
