# Generated by Django 5.1.2 on 2025-04-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ativo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ativo da frota')),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('RENAVAN', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('tipo_combustivel', models.CharField(blank=True, max_length=20, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('Galpao', 'Parado'), ('Manutenção', 'Manutenção'), ('Avariado', 'Avariado'), ('Operação', 'Operação'), ('Reservado', 'Reservado')], max_length=100, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Veiculos',
                'verbose_name_plural': 'Veiculo',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada_manutencao', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Motivo')),
                ('local_de_manutencao', models.CharField(blank=True, max_length=255, null=True)),
                ('operacao', models.CharField(blank=True, max_length=255, null=True)),
                ('registro', models.TextField(blank=True, max_length=5000, null=True)),
                ('custo_total', models.FloatField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='')),
                ('Attivo_em_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencao', to='operacional.frota', verbose_name='Ativo em manutencao')),
            ],
            options={
                'verbose_name': 'Manutencao',
                'verbose_name_plural': 'ordens de Manutenção',
            },
        ),
    ]
