# Generated by Django 5.1.2 on 2025-04-29 18:25

import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='Attivo_em_manutencao',
            new_name='Ativo_em_manutencao',
        ),
        migrations.AlterField(
            model_name='frota',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=utils.tools_utils.documentos_frota_load_path),
        ),
    ]
