# Generated by Django 5.1.2 on 2025-04-29 18:50

import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_rename_attivo_em_manutencao_manutencao_ativo_em_manutencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=utils.tools_utils.documentos_manutencao_frota_load_path),
        ),
    ]
