# Generated by Django 5.1.2 on 2025-04-30 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0003_alter_manutencao_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_ativo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de ativo',
                'verbose_name_plural': 'Tipos  de ativo',
            },
        ),
        migrations.AlterField(
            model_name='frota',
            name='tipo',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='frota', to='operacional.tipo_ativo', verbose_name='Tipo de ativo'),
            preserve_default=False,
        ),
    ]
