# Generated by Django 5.1.2 on 2025-04-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0004_tipo_ativo_alter_frota_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frota',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='frota', to='operacional.tipo_ativo', verbose_name='Tipo de ativo'),
        ),
    ]
