# Generated by Django 5.1.2 on 2025-05-06 15:58

import django.db.models.deletion
import django.utils.timezone
import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0006_alter_frota_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frota',
            name='documento',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=utils.tools_utils.documentos_frota_load_path),
        ),
        migrations.CreateModel(
            name='lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=100, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_entrada', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade_entrada_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Nf', models.FileField(upload_to=utils.tools_utils.documentos_amoxarifado_load_path)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.tipo_ativo', verbose_name='Tipo_de_ativo')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='Item_almoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('lotes', models.ManyToManyField(related_name='lotes', to='operacional.lote')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
