# Generated by Django 5.1.2 on 2025-05-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0007_alter_frota_documento_lote_item_almoxarifado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_almoxarifado',
            name='lotes',
        ),
        migrations.AddField(
            model_name='item_almoxarifado',
            name='lotes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='operacional.lote'),
            preserve_default=False,
        ),
    ]
