# Generated by Django 5.1.2 on 2025-05-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0008_remove_item_almoxarifado_lotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_almoxarifado',
            name='lotes',
        ),
        migrations.AddField(
            model_name='lote',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='operacional.item_almoxarifado', verbose_name='Item almoxarifado'),
            preserve_default=False,
        ),
    ]
