# Generated by Django 5.1.2 on 2025-05-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0009_remove_item_almoxarifado_lotes_lote_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='operacional.item_almoxarifado', verbose_name='Item almoxarifado'),
        ),
    ]
