# Generated by Django 5.1.2 on 2025-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0010_alter_lote_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
