# Generated by Django 5.1.2 on 2025-05-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0011_alter_lote_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='tipo',
        ),
        migrations.AddField(
            model_name='item_almoxarifado',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operacional.tipo_ativo', verbose_name='Tipo_de_ativo'),
            preserve_default=False,
        ),
    ]
