# Generated by Django 5.1.2 on 2025-05-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0012_remove_lote_tipo_item_almoxarifado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_almoxarifado',
            name='quantidade_total_estoque',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
