# Generated by Django 5.1.2 on 2025-05-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0013_item_almoxarifado_quantidade_total_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_almoxarifado',
            name='quantidade_total_estoque',
        ),
    ]
