# Generated by Django 5.1.2 on 2025-04-28 17:22

import django.utils.timezone
import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('pedido_origem', models.CharField(blank=True, choices=[('comercial', 'comercial'), ('financeiro', 'financeiro'), ('RH', 'RH'), ('Produção', 'Produção'), ('Administrador', 'Administrador')], max_length=100, null=True)),
                ('emissor', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio_emissor', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('certidao', 'Certidao'), ('licença', 'licença'), ('declração', 'declaração')], max_length=255, null=True)),
                ('data_emissao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=utils.tools_utils.documentos_load_path)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
    ]
