# Generated by Django 5.1.2 on 2024-11-19 21:38

import django.db.models.deletion
import processos.models
import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.CharField(max_length=50)),
                ('objeto', models.TextField(max_length=1200)),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('seguro', models.CharField(choices=[('SIM', 'POSSUI SEGURO'), ('NÃO', 'NÃO POSSUI SEGURO')], default=None, max_length=25)),
                ('tipo_documento', models.CharField(choices=[('apolice', 'apolice de seguro'), ('seg.boleto', 'boleto de seguro'), ('contrato', 'contrato assinado'), ('diversos', 'documentos diversos')], default='diversos', max_length=25)),
                ('documentos', models.FileField(blank=True, upload_to=utils.tools_utils.contrato_upload_path, validators=[processos.models.validade_pdf], verbose_name='Documentos')),
                ('seguradora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora')),
                ('inicio', models.DateTimeField()),
                ('vigencia', models.CharField(max_length=50)),
                ('fim_contrato', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Total')),
                ('observacoes', models.TextField(max_length=1800)),
                ('arquivos', models.FileField(blank=True, upload_to='processos/contratos', validators=[processos.models.validade_pdf], verbose_name='Arquivos')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, verbose_name='Processo ADM')),
                ('numero_licitacao', models.CharField(max_length=50, verbose_name='Licitação nª')),
                ('contratante', models.CharField(max_length=50)),
                ('modalidade', models.CharField(max_length=50)),
                ('data_disputa', models.DateTimeField()),
                ('objeto', models.TextField(max_length=500)),
                ('tipo', models.CharField(choices=[('GLOBAL', 'PREÇO GLOBAL'), ('LOTE', 'PREÇO POR LOTE'), ('ITEM', 'PREÇO POR ITEM'), ('MAIOR OFERTA', 'LEILAO E OU CESSÃO')], default=None, max_length=25)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('CADASTRAR', 'CADASTRAR PROPOSTA'), ('CADASTRADO', 'PROPOSTA CADASTRADA'), ('ACOMPANHAR', 'EM ACOMPANHAMENTO'), ('RECURSO', 'FAZER RECURSO'), ('CONTRA-RAZÃO', 'FAZER CONTRA RAZAO'), ('HOMOLOGADO', 'HOMOLAGADO'), ('ASSINADO', 'CONTRATO ASSINADO')], default=None, max_length=25)),
                ('ocorrencias', models.TextField(blank=True, max_length=500)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_origem', models.DateField(blank=True, null=True)),
                ('cnpj_contratante', models.CharField(default='', max_length=18)),
                ('contratante', models.CharField(default='', max_length=60)),
                ('empenho', models.CharField(default='', max_length=50)),
                ('ordem_fornecimento', models.CharField(blank=True, default='', max_length=50)),
                ('recebimento_empenho', models.DateField(blank=True, null=True)),
                ('nf', models.FileField(blank=True, upload_to='processo/contratos/pedidos/notas_fiscais/%Y/%m/')),
                ('contato', models.CharField(blank=True, default='', max_length=50)),
                ('telefone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('objeto', models.TextField(blank=True, default='', max_length=600)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('unidade_fornecimento', models.CharField(default='', max_length=50)),
                ('qtde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coordenador', models.CharField(default='', max_length=50)),
                ('show', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('RECEBIDO', 'PEDIDO RECEBIDO NA UNIDADE'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('EM EXECUÇÃO', 'SENDO PRESTADO(EXECUTADO)'), ('ENTREGUE', 'PEDIDO ENTREGUE'), ('FINALIZADO', 'OPERAÇÃO FINALIZADA'), ('EM ACEITE', 'AGUARDANDO APROVAÇÃO DO CLIENTE'), ('APROVADO', 'SERVIÇO OU PRODUTO APROVADO'), ('FATURADO', 'PARA EMITIR NOTA FISCAL'), ('NF EMITIDA', 'NF EMITIDA'), ('NF RETORNADA', 'NF RETORNADA POR ERRO'), ('NF PAGA', 'CLIENTE PAGOU'), ('FINALIZADO', 'PEDIDO FINALIZADO')], default=None, max_length=25)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='processos.contratos')),
            ],
        ),
        migrations.AddField(
            model_name='contratos',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='processos.processo'),
        ),
    ]
