# Generated by Django 5.1.2 on 2024-11-29 20:49

import django.db.models.deletion
import django.utils.timezone
import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante', models.CharField(max_length=50, verbose_name='Contratante')),
                ('objeto', models.TextField(max_length=1200, verbose_name='Objeto')),
                ('numero', models.CharField(default='', max_length=50)),
                ('seguro', models.CharField(blank=True, choices=[('', ''), ('SIM', 'POSSUI SEGURO'), ('NÃO', 'NÃO POSSUI SEGURO')], default='', max_length=25)),
                ('tipo_documento', models.CharField(blank=True, choices=[('', ''), ('apolice', 'apolice de seguro'), ('seg.boleto', 'boleto de seguro'), ('contrato', 'contrato assinado'), ('diversos', 'documentos diversos')], default='', max_length=25)),
                ('documentos', models.FileField(blank=True, upload_to=utils.tools_utils.contrato_upload_path, verbose_name='Documentos')),
                ('seguradora', models.CharField(blank=True, max_length=100, verbose_name='Seguradora')),
                ('apolice', models.CharField(max_length=100)),
                ('inicio', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('vigencia', models.CharField(blank=True, default='', max_length=50)),
                ('fim_contrato', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Valor Total')),
                ('observacoes', models.TextField(default='', max_length=1800)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, verbose_name='Processo ADM')),
                ('numero_licitacao', models.CharField(max_length=50, verbose_name='Licitação nª')),
                ('contratante', models.CharField(blank=True, max_length=50)),
                ('modalidade', models.CharField(choices=[('PE', 'PREGAO ELETRONICO'), ('PP', 'PREGÃO PRESENCIAL'), ('CC', 'CONCORRENCIA'), ('TP', 'TOMADA DE PREÇOS'), ('LE', 'LEILÃO'), ('DL', 'DISPENSA'), ('CD', 'COMPRA DIRETA'), ('COT', 'COTAÇÃO')], max_length=25)),
                ('data_disputa', models.DateTimeField(default=django.utils.timezone.now)),
                ('objeto', models.TextField(max_length=500, verbose_name='Objeto')),
                ('tipo', models.CharField(choices=[('GLOBAL', 'PREÇO GLOBAL'), ('LOTE', 'PREÇO POR LOTE'), ('ITEM', 'PREÇO POR ITEM'), ('MAIOR OFERTA', 'LEILAO E OU CESSÃO')], max_length=25)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('CADASTRAR', 'CADASTRAR PROPOSTA'), ('CADASTRADO', 'PROPOSTA CADASTRADA'), ('ACOMPANHAR', 'EM ACOMPANHAMENTO'), ('RECURSO', 'FAZER RECURSO'), ('CONTRA-RAZÃO', 'FAZER CONTRA RAZAO'), ('HOMOLOGADO', 'HOMOLAGADO'), ('ASSINADO', 'CONTRATO ASSINADO')], max_length=25)),
                ('ocorrencias', models.TextField(blank=True, max_length=500)),
                ('tipo_documento', models.CharField(blank=True, choices=[('', ''), ('EDITAL', 'EDITAL E ANEXOS'), ('BOOK', 'BOOK USADO'), ('PEÇAS JURIDICCAS', 'PEÇAS JURIDICAS'), ('DIVERSOS', 'DOCUMENTOS DIVERSOS')], default=None, max_length=25)),
                ('documentos', models.FileField(blank=True, upload_to=utils.tools_utils.processo_upload_path, verbose_name='arquivo')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_origem', models.DateField(blank=True, null=True)),
                ('cnpj_contratante', models.CharField(default='', max_length=18)),
                ('contratante', models.CharField(default='', max_length=60)),
                ('empenho', models.CharField(default='', max_length=50)),
                ('ordem_fornecimento', models.CharField(blank=True, default='', max_length=50)),
                ('recebimento_empenho', models.DateField(blank=True, null=True)),
                ('contato', models.CharField(blank=True, default='', max_length=50)),
                ('telefone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('objeto', models.TextField(blank=True, default='', max_length=600)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('unidade_fornecimento', models.CharField(default='', max_length=50)),
                ('qtde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coordenador', models.CharField(default='', max_length=50)),
                ('show', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('RECEBIDO', 'PEDIDO RECEBIDO NA UNIDADE'), ('EM PRODUÇÃO', 'EM PRODUÇÃO'), ('EM EXECUÇÃO', 'SENDO PRESTADO(EXECUTADO)'), ('ENTREGUE', 'PEDIDO ENTREGUE'), ('FINALIZADO', 'OPERAÇÃO FINALIZADA'), ('EM ACEITE', 'AGUARDANDO APROVAÇÃO DO CLIENTE'), ('APROVADO', 'SERVIÇO OU PRODUTO APROVADO'), ('FATURADO', 'PARA EMITIR NOTA FISCAL'), ('NF EMITIDA', 'NF EMITIDA'), ('NF RETORNADA', 'NF RETORNADA POR ERRO'), ('NF PAGA', 'CLIENTE PAGOU'), ('FINALIZADO', 'PEDIDO FINALIZADO')], default=None, max_length=25)),
                ('tipo_documento', models.CharField(choices=[('RELATORIOS', 'RELATORIOS'), ('PEDIDO', 'PEDIDO'), ('NOTAS REEMBOLSO', 'NOTAS DE REEMBOLSO'), ('NF PARA FATURA', 'NOTAS DE FATURAMENTO'), ('ACEITE', 'ACEITES'), ('DIVERSOS', 'ACEITES')], default='diversos', max_length=25)),
                ('documentos', models.FileField(blank=True, max_length=255, upload_to=utils.tools_utils.pedido_upload_path, verbose_name='Documentos ')),
                ('endereco_entrega', models.TextField(blank=True, default='', max_length=1800)),
                ('observacoes', models.TextField(blank=True, default='', max_length=1800)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='processos.contratos')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.AddField(
            model_name='contratos',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='processos.processo'),
        ),
    ]
