# Generated by Django 5.1.2 on 2024-11-20 02:00

import processos.models
import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratos',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='arquivos',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='documentos',
            field=models.FileField(blank=True, upload_to=utils.tools_utils.pedido_upload_path, verbose_name='Documentos '),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tipo_documento',
            field=models.CharField(choices=[('RELATORIOS', 'RELATORIOS'), ('PEDIDO', 'PEDIDO'), ('NOTAS REEMBOLSO', 'NOTAS DE REEMBOLSO'), ('NF PARA FATURA', 'NOTAS DE FATURAMENTO'), ('ACEITE', 'ACEITES'), ('DIVERSOS', 'ACEITES')], default='diversos', max_length=25),
        ),
        migrations.AddField(
            model_name='processo',
            name='documentos',
            field=models.FileField(blank=True, upload_to=utils.tools_utils.processo_upload_path, validators=[processos.models.validade_pdf], verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo_documento',
            field=models.CharField(choices=[('EDITAL', 'EDITAL E ANEXOS'), ('BOOK', 'BOOK USADO'), ('PEÇAS JURIDICCAS', 'PEÇAS JURIDICAS'), ('DIVERSOS', 'DOCUMENTOS DIVERSOS')], default='diversos', max_length=25),
        ),
    ]
