# Generated by Django 5.1.2 on 2024-12-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_pedidos_data_hora_att_pedidos_local_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='local_entrega',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='tipo_documento',
            field=models.CharField(choices=[('RELATORIOS', 'RELATORIOS'), ('PEDIDO', 'PEDIDO'), ('NOTAS REEMBOLSO', 'NOTAS DE REEMBOLSO'), ('NF PARA FATURA', 'NOTAS DE FATURAMENTO'), ('ACEITE', 'ACEITES'), ('DIVERSOS', 'ACEITES')], default='PEDIDO', max_length=25),
        ),
    ]
