# Generated by Django 5.1.2 on 2024-11-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_alter_contratos_options_alter_pedidos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='nf',
        ),
    ]
