# Generated by Django 5.1.2 on 2024-12-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_remove_pedidos_local_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='tipo_documento',
            field=models.CharField(choices=[('RELATORIOS', 'RELATORIOS'), ('PEDIDO', 'PEDIDO'), ('NOTAS REEMBOLSO', 'NOTAS DE REEMBOLSO'), ('NF PARA FATURA', 'NOTAS DE FATURAMENTO'), ('ACEITE', 'ACEITES'), ('DIVERSOS', 'ACEITES')], default='', max_length=25),
        ),
    ]
