# Generated by Django 5.1.2 on 2024-11-20 20:00

import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_remove_pedidos_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='fim_contrato',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='documentos',
            field=models.FileField(blank=True, max_length=255, upload_to=utils.tools_utils.pedido_upload_path, verbose_name='Documentos '),
        ),
    ]
