# Generated by Django 5.1.2 on 2024-11-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_alter_contratos_fim_contrato_alter_contratos_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='endereco_entrega',
            field=models.TextField(blank=True, default='', max_length=1800),
        ),
    ]
