# Generated by Django 5.1.2 on 2024-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_pedidos_endereco_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='observacoes',
            field=models.TextField(blank=True, default='', max_length=1800),
        ),
    ]
