# Generated by Django 5.1.2 on 2024-12-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_alter_pedidos_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('', ''), ('RELATORIOS', 'RELATORIOS'), ('PEDIDO', 'PEDIDO'), ('NOTAS REEMBOLSO', 'NOTAS DE REEMBOLSO'), ('NF PARA FATURA', 'NOTAS DE FATURAMENTO'), ('ACEITE', 'ACEITES'), ('DIVERSOS', 'ACEITES')], default='', max_length=25),
        ),
    ]
