# Generated by Django 5.1.2 on 2025-05-06 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0012_remove_lote_tipo_item_almoxarifado_tipo'),
        ('processos', '0006_alter_pedidos_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAlocado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aloccado', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total_alocado', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('item_alocado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.item_almoxarifado', verbose_name='Item alocado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.pedidos', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item alocado',
                'verbose_name_plural': 'Items alocados',
            },
        ),
    ]
