# Generated by Django 5.1.2 on 2024-11-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_pedidos_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.CharField(choices=[('PE', 'PREGAO ELETRONICO'), ('PP', 'PREGÃO PRESENCIAL'), ('CC', 'CONCORRENCIA'), ('TP', 'TOMADA DE PREÇOS'), ('LE', 'LEILÃO'), ('DL', 'DISPENSA'), ('CD', 'COMPRA DIRETA'), ('COT', 'COTAÇÃO')], default=None, max_length=25),
        ),
    ]
