# Generated by Django 5.1.2 on 2025-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_itemalocado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
