# Generated by Django 5.1.2 on 2024-11-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_contratos_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='apolice',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
