# Generated by Django 5.1.2 on 2025-05-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_pedidos_custo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='custo_total_contrato',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=18),
        ),
    ]
