# Generated by Django 5.1.2 on 2025-05-06 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0012_remove_lote_tipo_item_almoxarifado_tipo'),
        ('processos', '0009_contratos_custo_total_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemalocado',
            name='item_alocado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.item_almoxarifado', verbose_name='Items_alocados'),
        ),
    ]
