# Generated by Django 5.1.2 on 2024-11-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_alter_processo_data_disputa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_disputa',
            field=models.DateTimeField(),
        ),
    ]
