# Generated by Django 5.1.2 on 2025-05-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0012_remove_lote_tipo_item_almoxarifado_tipo'),
        ('processos', '0011_alter_itemalocado_item_alocado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemalocado',
            name='item_alocado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_alocados', to='operacional.item_almoxarifado', verbose_name='Itens alocados'),
        ),
    ]
