# Generated by Django 5.1.2 on 2024-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_alter_processo_data_disputa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='contratante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_disputa',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_licitacao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Licitação nª'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Processo ADM'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objeto',
            field=models.TextField(blank=True, max_length=500, verbose_name='Objeto'),
        ),
    ]
