# Generated by Django 5.1.2 on 2025-05-06 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0012_remove_lote_tipo_item_almoxarifado_tipo'),
        ('processos', '0012_alter_itemalocado_item_alocado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemalocado',
            name='preco_unitario_medio_pedido',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemalocado',
            name='item_alocado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.item_almoxarifado', verbose_name='Itens alocados'),
        ),
        migrations.AlterField(
            model_name='itemalocado',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_alocados', to='processos.pedidos', verbose_name='Pedido'),
        ),
    ]
