# Generated by Django 5.1.2 on 2024-11-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_alter_processo_contratante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('PE', 'PREGAO ELETRONICO'), ('PP', 'PREGÃO PRESENCIAL'), ('CC', 'CONCORRENCIA'), ('TP', 'TOMADA DE PREÇOS'), ('LE', 'LEILÃO'), ('DL', 'DISPENSA'), ('CD', 'COMPRA DIRETA'), ('COT', 'COTAÇÃO')], default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, choices=[('CADASTRAR', 'CADASTRAR PROPOSTA'), ('CADASTRADO', 'PROPOSTA CADASTRADA'), ('ACOMPANHAR', 'EM ACOMPANHAMENTO'), ('RECURSO', 'FAZER RECURSO'), ('CONTRA-RAZÃO', 'FAZER CONTRA RAZAO'), ('HOMOLOGADO', 'HOMOLAGADO'), ('ASSINADO', 'CONTRATO ASSINADO')], default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('GLOBAL', 'PREÇO GLOBAL'), ('LOTE', 'PREÇO POR LOTE'), ('ITEM', 'PREÇO POR ITEM'), ('MAIOR OFERTA', 'LEILAO E OU CESSÃO')], default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('EDITAL', 'EDITAL E ANEXOS'), ('BOOK', 'BOOK USADO'), ('PEÇAS JURIDICCAS', 'PEÇAS JURIDICAS'), ('DIVERSOS', 'DOCUMENTOS DIVERSOS')], default='diversos', max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
