# Generated by Django 5.1.2 on 2025-05-06 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0014_remove_item_almoxarifado_quantidade_total_estoque'),
        ('processos', '0013_itemalocado_preco_unitario_medio_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemalocado',
            name='item_alocado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_alocados', to='operacional.item_almoxarifado', verbose_name='Itens alocados'),
        ),
    ]
