# Generated by Django 5.1.2 on 2024-11-25 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_alter_processo_data_disputa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_disputa',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processo',
            name='modalidade',
            field=models.CharField(choices=[('PE', 'PREGAO ELETRONICO'), ('PP', 'PREGÃO PRESENCIAL'), ('CC', 'CONCORRENCIA'), ('TP', 'TOMADA DE PREÇOS'), ('LE', 'LEILÃO'), ('DL', 'DISPENSA'), ('CD', 'COMPRA DIRETA'), ('COT', 'COTAÇÃO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_licitacao',
            field=models.CharField(max_length=50, verbose_name='Licitação nª'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(max_length=50, verbose_name='Processo ADM'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='objeto',
            field=models.TextField(max_length=500, verbose_name='Objeto'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('CADASTRAR', 'CADASTRAR PROPOSTA'), ('CADASTRADO', 'PROPOSTA CADASTRADA'), ('ACOMPANHAR', 'EM ACOMPANHAMENTO'), ('RECURSO', 'FAZER RECURSO'), ('CONTRA-RAZÃO', 'FAZER CONTRA RAZAO'), ('HOMOLOGADO', 'HOMOLAGADO'), ('ASSINADO', 'CONTRATO ASSINADO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('GLOBAL', 'PREÇO GLOBAL'), ('LOTE', 'PREÇO POR LOTE'), ('ITEM', 'PREÇO POR ITEM'), ('MAIOR OFERTA', 'LEILAO E OU CESSÃO')], max_length=25),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('', ''), ('EDITAL', 'EDITAL E ANEXOS'), ('BOOK', 'BOOK USADO'), ('PEÇAS JURIDICCAS', 'PEÇAS JURIDICAS'), ('DIVERSOS', 'DOCUMENTOS DIVERSOS')], default=None, max_length=25),
        ),
    ]
