# Generated by Django 5.1.2 on 2025-01-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0006_alter_pedidos_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro_de_custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
            },
        ),
        migrations.CreateModel(
            name='Contas_a_pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.CharField(max_length=100)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credor', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('nota_fiscal_compra', models.CharField(max_length=100, verbose_name='nota fiscal')),
                ('numero_de_parcelas', models.IntegerField(default=1)),
                ('valor_das_parcelas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('A vencer', 'A vencer'), ('Vencida', 'Vencida')], default=None, max_length=250, null=True, verbose_name='status')),
                ('ocorrencias', models.TextField()),
                ('documentos', models.FileField(blank=True, null=True, upload_to='Pagamentos//%Y/%m/%d')),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=100)),
                ('conta_corrente', models.CharField(max_length=100)),
                ('Centrodecusto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.centro_de_custo')),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
            },
        ),
        migrations.CreateModel(
            name='Contas_a_receber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobrança', models.CharField(max_length=100)),
                ('contrato', models.CharField(max_length=100)),
                ('nota_fiscal', models.CharField(max_length=100)),
                ('valor_total_do_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('data_cobranca', models.DateField()),
                ('data_pgto', models.DateField()),
                ('status', models.CharField(choices=[('enviado', 'enviado'), ('Vencida', 'Vencida'), ('pago', 'pago')], default=None, max_length=250, null=True, verbose_name='status')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='A_receber/%Y/%m/%d')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.pedidos')),
            ],
            options={
                'verbose_name': 'Conta a receber',
                'verbose_name_plural': 'Contas a receber',
            },
        ),
    ]
