# Generated by Django 5.1.2 on 2025-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='financeiro/Pagamentos/%Y/%m/%d'),
        ),
    ]
