# Generated by Django 5.1.2 on 2025-01-09 18:07

import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_contas_a_pagar_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to=utils.tools_utils.docs_finan_load_path),
        ),
    ]
