# Generated by Django 5.1.2 on 2025-01-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_contas_a_pagar_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='Centrodecusto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrodecusto', to='financeiro.centro_de_custo'),
        ),
    ]
