# Generated by Django 5.1.2 on 2025-04-10 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_contas_a_pagar_centrodecusto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='Centrodecusto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrodecusto', to='financeiro.centro_de_custo', verbose_name='Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='vencimento',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
