# Generated by Django 5.1.2 on 2025-04-28 17:22

import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_contas_a_pagar_centrodecusto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_receber',
            name='arquivos',
            field=models.FileField(blank=True, null=True, upload_to=utils.tools_utils.docs_finan_load_path_rcbm),
        ),
    ]
